var lang = {
  acao: "Açao",
  adicionarProduto: "Adicionar Produto",
  aliqICMS: "Aliq. ICMS",
  alterar: "Alterar",
  ano: "Ano",
  anoFabricacao: "Ano Fabricação",
  anoModelo: "Ano Modelo",
  bairro: "Bairro",
  baseCalcIcms: "Base de Cálc ICMS Substituição",
  caixa: "CAIXA",
  cancelar: "Cancelar",
  carro: "Carro",
  carroChefe: "Carro Chefe",
  carroVenda: "Carro de Venda",
  cartao: "Cartão",
  cartao2: "2 - Cartão",
  categoria: "Categoria",
  CFOP: "CFOP",
  chaveNFe: "Chave NFe",
  cheque: "Cheque",
  cheque3: "3 - Cheque",
  cidade: "Cidade",
  cliente: "Cliente",
  cnpjTransportadora: "CNPJ da Transportadora",
  codANTT: "Código ANTT",
  codigoBarra: "Código de Barras",
  combustivel: "Combustível",
  complemento: "Complemento",
  comprador: "Comprador",
  concluido: "CONCLUÍDO",
  devolucao: 'Devolução',
  montagem: 'Montagem',
  consulta: "Consulta",
  cor: "Cor",
  creditoUsado: "Crédito Usado",
  credito: "Crédito",
  dadosCliente: "Dados do Cliente",
  dadosDevolucao: "Dados da Devolução",
  dadosOrcamento: "Dados do Orçamento",
  itensOrcamento: 'Itens Orçamento',
  data: "Data",
  dataFinal: "Data Final",
  dataInicial: "Data Inicial",
  dataVencimento: "Data do Vencimento",
  deposito8: "8 - Depósito",
  desconto: "Desconto",
  descontoVendedor: "Desconto Vendedor",
  descProduto: "Descrição Produto",
  descProdutoCompl: "Descrição Produto Completa",
  destinatario: "Destinatário",
  detalhado: "Detalhado",
  detalhado5: "5 - Detalhado",
  detalheCliente: 'Detalhe do Cliente',
  dinheiro: "Dinheiro",
  dinheiro1: "1 - Dinheiro",
  dtEmissao: "Data de Emissão da Nota",
  editar: "Editar",
  editarItem: "Editar Item",
  emitente: "Emitente",
  encerrado: "Encerrado",
  encerrar: 'Encerrar',
  endereco: "Endereço",
  endEstoque: "End Estoque",
  entregarReceber6: "6 - Entregar e Receber",
  entregarReceber: "Entreg Receb",
  especie: "Espécie",
  excluir: "Excluir",
  excluirItem: "Excluir Item",
  finalizar: "Encerrar",
  financeiro: "Financeiro",
  formaPagamento: "Forma de Pagto",
  foto: "Ft",
  freteConta: "Frete Por Conta",
  funcionarioQueRealizou: "Funcionário que Realizou",
  imprimir: "Imprimir",
  informacoesComplementares: "Informações Complementares",
  informativo: "Informativo",
  IPI: "Aliq. IPI",
  item: "Item",
  kmAtual: "KM Atual",
  kmFuturo: "KM Futuro",
  limite: "Limite",
  listaHistoricoProduto: "Lista Histórico Produto",
  localizadorAntigo: "Localizador Antigo",
  localizar: "Localizar",
  localPessoa: "Local / Pessoa",
  locCliente: "Localizar Cliente (Nome e ou CNPJ-CPF)",
  marca: "Marca",
  marcaModelo: "Marca / Modelo",
  mes: "Mês",
  motorista: "Motorista",
  nomeCliente: "Nome Cliente",
  nomeFornecedor: "Nome do Fornecedor",
  fornecedor: "Fornecedor",
  nomeTransportadora: "Nome da Transportadora",
  novaDevolucao: "Nova Devolução",
  novo: "Novo",
  novoCarroVenda: "Novo Carro de Venda",
  nr: "Nº",
  nrChassi: "Nº Chassi",
  nrRenavan: "Nº RENAVAN",
  nrRequisicao: "Nº Requisição",
  nrCF: "Nº Cupom Fiscal",
  numDevolucao: "Nº Devolução",
  numero: "Número",
  numFabricante: "Nº Fabricante",
  numFabricante2: "Nº Fabricante 2",
  numNota: "Nº da Nota",
  numOrcamento: "Nº Orçamento",
  obrigatorio: "Obrigatório",
  obs: "Observações",
  observacao: "OBS",
  orcamento: "Orçamento",
  orderServico: "Ordem de Serviço",
  outrasdespesasacessorias: "Outras Despesas Acessórias",
  pedido4: "4 - Pedido",
  pedido: "Pedido",
  periodo: "Período",
  pesoBruto: "Peso Bruto",
  pesoLiquido: "Peso Líquido",
  placa: "Placa",
  preco: "Preço",
  precoCustoNFe: "O preço de custo tem que ser igual ao da Nota Fiscal Eletrônica",
  producao: "Produção",
  produto: "Produto",
  qtdLitros: "Qtd Litros",
  qto: "Qto",
  quantidade: "Quantidade",
  referenciaMesAno: "Referência Mês / Ano",
  requisicao: "Requisição",
  salvar: "Salvar",
  selecioneFuncionario: "Selecione um Funcionário",
  selecioneCliente: 'Selecione um cliente para continuar',
  funcionario: "Funcionário",
  selecioneMarca: "Selecione uma Marca",
  showDevolucao: "Exibir Dados da Devolução",
  situacao: "Situação",
  somatorio: "somatório",
  subTotal: "Sub.Total",
  telefone: "Telefone",
  tipo: "Tipo",
  tipoDocumento: "Tipo do Documento",
  tipoMovimentacao: "Tipo",
  tipoPagamento: "Tipo de Pagamento",
  total: "Total",
  uf: "UF",
  UFCarro: "UF Carro",
  unidade: "UN",
  valePeca7: "7 - Vale Peça",
  valePeca: "Vale Peça",
  valor: "Valor",
  valorCalcIcms: "Valor do ICMS Substituição",
  valorCusto: "Valor Custo",
  valorDesconto: "Valor Desc",
  valorFrete: "Valor Frete",
  valorLitro: "R$ Litro",
  valorNota: "Valor da Nota",
  valorOrcamento: "Valor do Orçamento",
  valorReal: "Valor Real",
  valorTotal: "R$ Total",
  vendedor: "Vendedor",
  entrada: "Entrada",
  saida: "Saída",
  semana: "Semana",
  justificativa: "Justificativa",
  jeneiro: "Janeiro",
  fevereiro: "Fevereiro",
  marco: "Março",
  abril: "Abril",
  maio: "Maio",
  junho: "Junho",
  julho: "Julho",
  agosto: "Agosto",
  setembro: "Setembo",
  outubro: "Outubro",
  novembro: "Novembro",
  dezembro: "Dezembro",
  dataAdmissao: 'Data Admissão',
  cargo: "Cargo",
  assinaturaGerente: 'Assinatura Gerente',
  lancarNF: 'Lançar na NF',
  lancarMulta: 'Lançar Multa',
  qtdParcelas: 'Qtd Parcelas',
  inicioAlmoco: 'Inicio Almoço',
  fimAlmoco: 'Fim Almoço',
  chegada: 'Chegada',
  horario: 'Horário',
  F1LocalizacaoRapida: 'F1 Consumidor',
  //------------------------------------
  msgInformeDataInicial: "Informe uma Data Inicial",
  msgImagemMuitoGrande: 'Imagem muito grande, selecione outra',
  msgImagemMuitoPequena: 'Imagem muito pequena, selecione outra',
  msgInformeDataFinal: "Informe uma Data Final",
  msgAntesRemoverDesconto: "Antes de remover um item é necessário retirar o desconto",
  msgNaoLocalizado: "Item não Localizado",
  msgGostariaExcluirOrc: "Gostaria de Excluir este orçamento <br/> Nº Orçamento = ",
  msgNaoExisteOrcExcluir: "Não existe orçamento para ser excluído.",
  msgQtoObrigatorio: "A Quantidade  tem que ser maior que 0 (zero)",
  msgValorObrigatorio: "O Valor Custo tem que ser maior que 0 (zero)",
  msgValorSuperior: "O Valor valor superior ao permitido. Produto sem margem para desconto",
  msgProdutoNaoPodeSerAdd: 'Este produto não pode ser adicionado valor gual a zero',
  msgValorNaoPermiditdo: 'Valor não permitido, preço inferior ao de venda',
  msgQuantidadeMaiorEstoque: 'Quantidade maior que tem no estoque, gostaria de venda assim mesmo?',
  msgValorVendaIgualZero: 'Valor do produto está com o valor igual a 0 (zero)',
  msgQuantidadeInvalida: 'Quantidade inválido verifique',
  msgIPIObrigatorio: "IPI é obrigatória informe um valor",
  msgICMSObrigatorio: "ICMS é obrigatória informe um valor",
  msgDuplicidaeProduto: "Este produto já foi adicionado.",
  msgCaracteresNaNota: 'Número da Nota Fiscal contém caracteres inválidos, operação cancelada!',
  msgFaltaDadosFornecedor: 'Informe os Dados do Fornecedor, operação cancelada!',
  msgNenhumaNotaParaExcluir: 'Não existe nota selecionada para exclusão, operação cancelada!',
  msgNotaForaProducao: 'Nota não esta em produção, exclusão cancelada!',
  msgMudarSituacaoNotaEncerrado: 'Gostaria de mudança a situação para ENCERRADO?',
  msgMudarSituacaoNotaProducao: 'Gostaria de voltar situação para PRODUÇÃO?',
  msgOrcamentoNoCaixaGostaria: 'Orçamento no Caixa Gostaria de resgatá-lo?',
  msgCodigoInvalido: "código inválido",
  msgVeriDuplicidade: 'Verificando Duplicidade',
  msgFabricanteCadastrado: 'Nº Fabricante já está cadastrado',
  msgFabricanteCadastrado2: 'Nº Fabricante2 jpa está cadastrado',
  msgCadastaProdAnte: 'Cadastre o produto só depois e permitido a adição de um novo carro de venda',
  msgServidorOff: 'Servidor não está respondendo sua solicitação, tente mais tarde.',
  msgDeletarFalta: 'Gostaria de deletar esse registro?',
  msgDeletarItenOrcamento: 'Gostaria de deletar esse item do Orçamento?',
  msgUsuario: 'Usuário ou Senha não confere, verifique',
  msgUsarioNaoPreenchido: 'Usuário deve ser preenchido',
  msgSenhaNaoPreenchida: 'Informe uma senha para continuar',
  //-------------------------------------
  pnGeraNovoOrcamentoTitulo: "Gerar novo Orçamento",
  pnAguardeProcessoTitulo: "Aguarde o processo",
  pnAguardePeca: "Aguarde Carregando Peça",
  pnMensagemTitulo: "Mensagem do Sistema",
  pnCaculadora: "Calculadora",
  pnGraficoVenda: 'Gráfico de Vendas',
  //-----------Titulo Paginas-------------------
  titlePrincipal: "Siap - Sistema Integrado de Auto Peças",
  titleNotaEntradaLocalizar: "Localizar Nota de Entrada",
  titleTransportadoraLocalizar: "Localizar Transportadora",
  titleDevolucaoNFe: "Devolução Nota Fiscal Eletrônica",
  titleDevolucaoLocalizar: "Localizar Devolução",
  titleDevolucaoNova: "Nova Devolução",
  titleDevolucaoAlterar: "Alterar Dados da Nota de Devolução",
  titleDadosFornecedor: "Dados do Fornecedor",
  titleDadosTransportadora: "Dados da Transportadora",
  titleDadosDevolucao: "Dados da Devolução",
  titleItensNotaFiscal: "Itens da Nota Fiscal",
  titleAdicionarItem: "Adicionar item",
  titleExcluirItemDevolucao: "Confirma a exclusão deste Item da Nota de Devolução?",
  titleExcluirDevolucao: "Confirma a exclusão desta Nota de Devolução?",
  titleDadosNotaCompra: 'Dados da Nota de Compra',
  titlePecasVendidas: 'Peças Vendidas',
  titleCadastroVeiculos: 'Cadastro de Veículos da Rede Real',
  titleDocumentosVeiculos: 'Documentos do Veículo',
  titleMovimentacoesVeiculos: 'Movimentações do Veículo',
  titleManutencaoVeiculos: 'Manutenções do Veículo',
  titleAbastecimentoVeiculos: 'Abastecimentos do Veículo',
  titleMultasVeiculos: 'Multas do Veículo',
  //--------fim titulo paginas-------------------
  erro: "Ops, o servidor esta meio estranho é não esta respondendo"
};

//$(document).ready(function () {
$("[data-role]").each(function () {
//$(document).each('[data-role]', function () {
  var strTr = lang[$(this).attr('data-role')];
  $(this).html(strTr);
});


//});

